name: image_client
description: "Image Fetching App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.1
dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  stream_transform: ^2.0.0
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  retrofit: ^4.4.0
  dio: ^5.7.0
  logger: ^2.4.0  # for logging purpose
  get_it: ^7.7.0
  cached_network_image: ^3.3.1
  mockito: ^5.4.4
  golden_toolkit: ^0.15.0
dev_dependencies:
  retrofit_generator: '>=8.0.0 <10.0.0' # for Dart 3.3 use ^9.0.0
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  test: ^1.25.7
flutter:
  uses-material-design: true
